project:
  type: website
theme: pulse
execute:
  freeze: auto
date: last-modified  
format:
  html: 
    toc: true
    css: tweaks.css


website:
  title: "digitalcomplutensian"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "The Original"
        file: complutensian/index.qmd        
      - text: "Applications"
        file: examples/index.qmd
      - text: "Resources"
        file: resources/index.qmd
      - text: "Background"
        file: background/index.qmd  
      - text: "Who we are"
        file: who/index.qmd  

    right:
      - icon: person-circle
        menu:
          - text: "Neel Smith: home page"
            href: https://neelsmith.quarto.pub
        aria-label: Home  

  sidebar:
    - title: "Home"
      contents:
        - index.qmd  
    - title: "The Complutensian"
      contents:        
        - examples/index.qmd
        - examples/pluto/index.qmd
        - examples/quarto/index.qmd
    - title: "The Complutensian"
      contents:
        - complutensian/index.qmd
        - complutensian/images/index.qmd              
        - text: "---"        
        - text: "Organization"     

        - text: "---"   
        - complutensian/organization/titlepages/index.qmd
        - complutensian/organization/colophons/index.qmd
        - complutensian/organization/registers/index.qmd  
        - text: "Collation" 
        - complutensian/organization/prologs/index.qmd   
        - text: "---"                  
        - complutensian/pagetour/index.qmd
        - complutensian/navigation/index.qmd        
        - text: "---"           
        - text: "Chronology"


 

