---
engine: julia
title: Morphological data
---


```{julia}
#| echo: false
#| warn: false
#| output: false
using Pkg
Pkg.add("OpenScripturesHebrew")
Pkg.add("BrownDriverBriggs")
Pkg.add("Kanones")
Pkg.add("Tabulae")
Pkg.add("CitableParserBuilder")
```


## Hebrew

We are working with two existing sets of data with morphological annotations on the Hebrew Bible.


### Open Scriptures Hebrew Bible

The [Open Scriptures Hebrew Bible](https://hb.openscriptures.org) project (OSHB) includes manual annotations on everyword of the Hebrew, including a detailed morphological analysis. Lexemes are identified with Strong numbers. RThe OSHB data set is available on [github here](https://github.com/openscriptures/morphhb).




#### Julia package
Neel Smith has published `OpenScripturesHebrew.jl`, a Julia package for working with this data set. (See the [documentation](https://neelsmith.quarto.pub/openscriptureshebrew/).)

#### Example of usage

```{julia}
#| warn: false
#| output: false
using OpenScripturesHebrew
allwords = tanakh()
```
```{julia}
length(allwords)
```
```{julia}
allwords[3]
```
```{julia}
allwords[3].mtoken
```
```{julia}
parseword(allwords[3] )
```


### Sefaria

The [Sefaria project](https://www.sefaria.org/texts) makes its data available through an API [documented here](https://developers.sefaria.org/reference/getting-started-with-your-api). The API includes an option to [search Sefaria's online lexica](https://developers.sefaria.org/reference/get_api-words-word) for articles based on any form of a Hebrew word. Sefaria's search results include identifiers for Brown-Driver-Briggs (among others), which for our morphological anlayses are often more helpful than the Strong identifiers used by OSHB. While the Sefaria queries do not include detailed morphological analysis, it is possible to find part of speech codes in the related data, taken from Strong.

#### Precompiled data sets

The response time to a query using Sefaria's API is typically in tenths of a second. While this is perfectly adequate for interactive usage, it is impractical for application to a corpus with more than 400,000 words. At that speed, a single pass over the Hebrew Bible would require more than 11 hours (400,000 queries × 0.1 second = 40,000 seconds), and in practice automated runs of queries often time result in time out errors after only a few hundred queries.  For our morphological analysis, we have therefore compiled a set of static files with Sefaria's resolution

```
urn|form|lemma|bdbid
urn:cts:compnov:bible.genesis.masoretic_tokens:1.1.2|בָּרָ֣א|בָּרָא|BDB01439
```

####  Interactive use

Neel Smith has published `BrownDriverBriggs.jl`, a Julia package for working with this data set. (See the [documentation](https://neelsmith.quarto.pub/browndriverbriggs/).)

#### Example of usage

```{julia}
using BrownDriverBriggs 
articles = bdb("בָּרָ֣א")
```



## Greek

http://shot.holycross.edu/morphology/complutensian-current.cex


:::{.callout-note title="TBA"}
Links and summary of status TBA
:::


## Latin


:::{.callout-note title="TBA"}
Links and summary of status TBA
:::


- Using [Tabulae system](https://neelsmith.quarto.pub/tabulae/)

Prebuilt parsers:

- orthography of Vulgate: http://shot.holycross.edu/tabulae/complut-lat25-current.cex
- orthography of glosses: http://shot.holycross.edu/tabulae/complut-lat23-current.cex




### Example of usage

```{julia}
using Tabulae, CitableBase
url = "http://shot.holycross.edu/tabulae/core-lat25-current.cex"
parser = tabulaeStringParser(url, UrlReader)
parsetoken("creavit", parser)
```