---
engine: julia
---



# The prologs

Links are to illustrations in the Madrid copy of the Complutensian Bible.



1. *Dedication to Pope Leo X*
    - volume 1: quire `+` (initialquire), [page 2 recto](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v1p7)
    - volume 2: quire `title`  (initialquire), [page 1 verso](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v2a_p4) 
    - volume 3: quire `aaa` (initialquire), [page 1 verso](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v3a_p22)
    - volume 4: quire `a` (initial quire), [page 1 verso](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v4a_p2)  
2.  *To the reader, on reading the Old Testament*.
    - volume 1:  quire `+` (initialquire), [page 2 verso](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v1p8)
    - volume 2:  quire `prolog`, [page 1 recto](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v2a_p17)[^placement]
    - volume 3: quire `aaa` (initialquire), [page 2 recto](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v3a_p22)  
    - volume 4: quire `a` (initial quire), [page 2 recto](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v4a_p3)
3. *Finding roots of Hebrew words*.
    - volume 1:  quire `+` (initialquire), [page 3 recto](https://www.homermultitext.org/ict2/?urn=urn:cite2:citebne:complutensian.v1:v1p9)
4.  Prolog to Greek NT.
    - volume 1: vol1_+_4r
    - volume 5 vol5_a-preface_2r. Greek
    - volume 5 vol5_a-preface_2v. Latin. Incipit *Ne mireris aut vitio vertas o studiose lector*
5. Prolog to Hebrew and Aramaic dictionary.
    - volume 1 vol1_+_4r-vol1_+_4v

[^placement]: In volume 2, the title page and the prolog to the reader are each single sheets that have been tipped in. In the Madrid copy, the address to the reader is mistakenly placed between the first and second quires of the book of *Joshua* (quires `a` and `b`).

## Papal authorization

1. Papal authorization (only handwritten version in BNE text!)
    - volume 1 vol1_+_7v. In Huntington copy, see image [urn:cite2:citehunt:complutensian.v1:v1_plus_7v](https://www.homermultitext.org/ict2/?urn=urn:cite2:citehunt:complutensian.v1:v1_plus_7v)



## Historical context reproduced from other incunabula

1. Note on translations. Inicipit *Notandum: quod translatores et interpretes bibliae multi fuerunt*
    - volume 1 vol1_+_4v-vol1_+_5r
2. How to understand sacred scripture. Incipit: *Modi intelligendi sacram scripturam.  Notandum: quod omnis sacra scriptura quadriformi ratione distinguitur*
    - volume 1 vol1_+_5r

## Historical documents

(not including Jerome's prefaces to individual pieces of the Bible)

1. Letter of Jerome to Paulinus (letter 53). Chapter numbers given at end of each block   
    - volume 1 vol1_+_5r-vol1_+_6v
2. Letter of Eusebius to Carpianus
    - volume 5  vol5_a-preface_3r 
3.  Letter of Jerome to Pope Damasus
    - volume 5 vol5_a-preface_3v : 
