---
title: The printed Complutensian Bible
engine: julia
---


:::{.callout-tip title="Tip: see images in context"}
Learn more about [how images are displayed](./images/) in this guide to the Complutensian Bible.
:::
```{julia}
#| echo: false
#| warning: false
#| output: asis

#=
Fill these out:


## What was the purpose of the Complutensian polyglot Bible?

- The [editors' goals](./goals/)

## How are the six volumes organized?

- [Contents and organization](./organization/)
- References:
    - [title pages](./organization/titlepages/)
    - [prologs](./organization/titlepages/)
    - [colophons](./organization/colophons/)
    - [quire registers](./organization/registers/)
    - [collation](./organization/collation/)



## How does a reader use it?

- [Tour of a page](./pagetour/)
- [Combining indexes and texts for philological research](./navigation/)

## When was it created?

- [Dating the individual parts of the Complutensian](./chronology/)





=#
```

## What was the purpose of the Complutensian polyglot Bible?

- The editors' goals

## How are the six volumes organized?

- Contents and organization
- References:
    - [title pages](./organization/titlepages/)
    - [prologs](./organization/prologs/)
    - [colophons](./organization/colophons/)
    - [quire registers](./organization/registers/)
    - complete collation



## How does a reader use it?

Multilingual reading regardless of experience with the languages:

- [Tour of a page](./pagetour/) (*in progress*)

Reference materials for cutting-edge cross-lingual philology:

- [Combining indexes and texts for philological research](./navigation/)

## When was it created?

- Dating the individual parts of the Complutensian









