---
title: Pluto notebooks
engine: julia
---

:::{.callout-note title="Pluto"}
If you're not familiar with Pluto notebooks, here's a little  [more information](./pluto-about/) about them.
:::


One technology that is a good match for exploratory small-digital scholarship is Pluto, a reactive notebook system that runs in a browser. On this page we're gathering examples of Pluto notebooks working with our datasets.


### The physical organization of Complutensian and orthographic practices

- [browse images](./imagebrowsing/)
- [table of contents](./toc/): index of texts to images
- [passages of text indexed to browsable image](./passage-plus-image/) 
- [Latin spacing markers](./spacing-markers-latin/)
- orthographic practice: usage of [abbreviations in glosses](./abbreviations/) (*Documentation incomplete*)


### Editing and indexing

- [validating editing](./validation/): image and text views



### Reading passages of texts and glosses

- browse [text passages in the four versions of the Complutensian Bible](./alignedpassages/)
- browse [text passages and associated Latin glosses](./aligned-with-glosses/) (*Documentation incomplete*)
- [paired reader](./paired-reader/) (*Documentation incomplete*)
- [citable tokens](./citable-tokens/) (*Documentation incomplete*)


### Morphological analysis


- [morphology of the Greek Septuagint](./greek-morphology/)
- [find and identify verb forms](./greek-verbs/) for passages in Greek
- [isolate verb forms in passages of Greek](./isolate-verbs-greek/) (*Documentation incomplete*)
- [isolate verbs in Latin documents](./isolateverbs/) (*Documentation incomplete*)
- [Hebrew verbs](./hebrew-verbs/) (*Documentation incomplete*)

### Comparing  textual contents

- [compare verbal usage in Latin glosses and Vulgate](./glossing-vocab/)  (*Documentation incomplete*)
- [Zipf's law in Latin texts](./zipf-latin/): token frequencies (*Documentation incomplete*)
- [histograms of verbs](./verbhisto/) (*Documentation incomplete*)


### Aligning features

- [aligning verb functions](./align-verbs-multilingual/) across languages
- [align texts to a Latin verb](./align-verbs-to-latin/) (*Documentation incomplete*)

